#!/bin/bash
sudo apt-get update && sudo apt-get dist-upgrade && apt-get autoremove && apt-get autoclean && apt-get clean
uname -a 
dpkg -l 'linux-[ihs]*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\([-0-9]*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' | tee zu_entfernende_Kernel 
cat zu_entfernende_Kernel | xargs sudo apt-get -y purge 
rm zu_entfernende_Kernel 
exit
